openapi: 3.0.0
info:
  title: APIs Admin do Open Banking Brasil
  description: As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
  version: 1.1.0-rc
  contact:
    email: apiteam@swagger.io
servers:
  - url: http://api.banco.com.br/open-banking/admin/v1
tags:
- name: Metrics
paths:
  /metrics:
    get:
      tags:
        - Metrics
      summary: Obtém as métricas de disponibilidade das APIs
      description: Obtém as métricas de disponibilidade das APIs
      operationId: getMetrics
      parameters:
        - $ref: ./parameters/Page.yaml
        - $ref: ./parameters/PageSize.yaml
        - in: query
          name: period
          schema:
            type: string
            enum:
              - CURRENT
              - ALL
          required: false
          description: |
            Período a ser consultado
              * `CURRENT` - Métricas do dia atual.
              * `ALL` - Métricas de todo o período disponível.
      responses:
        '200':
          description: Dados das métricas
          content:
            application/json:
              schema:
                $ref: ./schemas/ResponseMetricsList.yaml
