name: Run Spectral

on:
  push:
    branches:    
      - '**'

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: 'documentation/source/swagger/*.yaml'
